#
# more information can be found here http://sonata-project.org/bundles/user
#
fos_user:
    db_driver:      propel # can be orm or odm
    firewall_name:  main
    user_class:     Sonata\UserBundle\Propel\User

    group:
        group_class: Sonata\UserBundle\Propel\Group
